local Modem = loadfile("/Modem.lua")()
Modem:Init()
local Communication = loadfile("/Communication.lua")()
Communication:Init(Modem)

Modem:Transmit(Communication.Config.SERVER_TO_CLIENT, Communication.Config.CLIENT_TO_SERVER, "if turtle.detect() then turtle.dig() turtle.placeUp() else turtle.digUp() turtle.place() end", "CLIENT_POWER_JUNCTION_1_5")

local d = Modem:Receive(Communication.Config.CLIENT_TO_SERVER)
print(textutils.serialize(d))

Modem:Transmit(Communication.Config.SERVER_TO_CLIENT, Communication.Config.CLIENT_TO_SERVER, "sleep(4)", "CLIENT_POWER_JUNCTION_1_5")
local d = Modem:Receive(Communication.Config.CLIENT_TO_SERVER)
print(textutils.serialize(d))
Modem:Transmit(Communication.Config.SERVER_TO_CLIENT, Communication.Config.CLIENT_TO_SERVER, "if turtle.detect() then turtle.dig() turtle.placeUp() else turtle.digUp() turtle.place() end", "CLIENT_POWER_JUNCTION_1_5")
local d = Modem:Receive(Communication.Config.CLIENT_TO_SERVER)
print(textutils.serialize(d))
Modem:Transmit(Communication.Config.SERVER_TO_CLIENT, Communication.Config.CLIENT_TO_SERVER, "sleep(2)", "CLIENT_POWER_JUNCTION_1_5")
local d = Modem:Receive(Communication.Config.CLIENT_TO_SERVER)
print(textutils.serialize(d))
Modem:Transmit(Communication.Config.SERVER_TO_CLIENT, Communication.Config.CLIENT_TO_SERVER, "if turtle.detect() then turtle.dig() turtle.placeUp() else turtle.digUp() turtle.place() end", "CLIENT_POWER_JUNCTION_1_5")
local d = Modem:Receive(Communication.Config.CLIENT_TO_SERVER)
print(textutils.serialize(d))
Modem:Transmit(Communication.Config.SERVER_TO_CLIENT, Communication.Config.CLIENT_TO_SERVER, "sleep(2)", "CLIENT_POWER_JUNCTION_1_5")
local d = Modem:Receive(Communication.Config.CLIENT_TO_SERVER)
print(textutils.serialize(d))
Modem:Transmit(Communication.Config.SERVER_TO_CLIENT, Communication.Config.CLIENT_TO_SERVER, "if turtle.detect() then turtle.dig() turtle.placeUp() else turtle.digUp() turtle.place() end", "CLIENT_POWER_JUNCTION_1_5")
local d = Modem:Receive(Communication.Config.CLIENT_TO_SERVER)
print(textutils.serialize(d))
Modem:Transmit(Communication.Config.SERVER_TO_CLIENT, Communication.Config.CLIENT_TO_SERVER, "sleep(2)", "CLIENT_POWER_JUNCTION_1_5")
local d = Modem:Receive(Communication.Config.CLIENT_TO_SERVER)
print(textutils.serialize(d))
Modem:Transmit(Communication.Config.SERVER_TO_CLIENT, Communication.Config.CLIENT_TO_SERVER, "if turtle.detect() then turtle.dig() turtle.placeUp() else turtle.digUp() turtle.place() end", "CLIENT_POWER_JUNCTION_1_5")
local d = Modem:Receive(Communication.Config.CLIENT_TO_SERVER)
print(textutils.serialize(d))
